name: Version Check

on:
  push:
    tags:
      - 'v*'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract tag version
        id: tag
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          echo "version=$TAG" >> $GITHUB_OUTPUT
          echo "Tag version: $TAG"

      - name: Extract package.json version
        id: package
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Package version: $VERSION"

      - name: Compare versions
        run: |
          if [ "${{ steps.tag.outputs.version }}" != "${{ steps.package.outputs.version }}" ]; then
            echo "❌ ERROR: Tag version (${{ steps.tag.outputs.version }}) doesn't match package.json version (${{ steps.package.outputs.version }})"
            echo ""
            echo "Fix this by running:"
            echo "  npm version ${{ steps.tag.outputs.version }} --no-git-tag-version"
            echo "  git add package.json"
            echo "  git commit -m 'chore: bump version to ${{ steps.tag.outputs.version }}'"
            echo "  git tag v${{ steps.tag.outputs.version }}"
            echo "  git push origin main --follow-tags"
            exit 1
          fi
          echo "✅ Versions match!"
